### ISSUE TITLE
The AUTH_KEY_UNREGISTERED error will appear no more than 2 days after login

### ISSUE THREAD

**Issue by wind-hx** [3bl3gamer/tgclient#19]
```
cfg := &mtproto.AppConfig{
		AppID:          int32(apiId),
		AppHash:        apiHash,
		AppVersion:     "4.8.3 x64",
		DeviceModel:    "82GH",
		SystemVersion:  "Windows 10",
		SystemLangCode: "en",
		LangPack:       "",
		LangCode:       "en",
	}
```
I think there is nothing wrong with the client configuration

**Comment by 3bl3gamer** [comment]
Looks strange. Are you 100% sure the session file is not modified externally?

People are also saying this sometimes happen under some conditions due to Telegram anti-spam/security measures. For example [here](https://ru.stackoverflow.com/questions/1322690/401-auth-key-unregistered-telegram) someone got this error after sending session file to another PC. Another person [suggests](https://github.com/sochix/TLSharp/issues/842#issuecomment-465119275) this happens because of virtual numbers and/or spam-like activity. Doesn't some of this sound similar to your case?
